# Generated by Django 4.2.5 on 2023-10-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0002_user_remove_webpage_topic_delete_accessrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.CreateModel(
            name="UserProfileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_site", models.URLField(blank=True)),
                ("profile_pic", models.ImageField(blank=True, upload_to="profile_pic")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="first_app.user"
                    ),
                ),
            ],
        ),
    ]
