# Generated by Django 4.2.5 on 2023-10-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfoApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=264)),
                ("email", models.CharField(max_length=264, unique=True)),
                ("password", models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileInfoApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_site", models.URLField(blank=True)),
                ("profile_pic", models.ImageField(blank=True, upload_to="profile_pic")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appFive.userinfoapp",
                    ),
                ),
            ],
        ),
    ]
