# Generated by Django 4.2.5 on 2023-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appFive", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofileinfoapp",
            old_name="profile_site",
            new_name="profile_site_app",
        ),
        migrations.RemoveField(
            model_name="userprofileinfoapp",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="userprofileinfoapp",
            name="profile_pic_app",
            field=models.ImageField(blank=True, upload_to="profile_pic_app"),
        ),
    ]
