# Generated by Django 4.2.5 on 2023-10-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "appFive",
            "0002_rename_profile_site_userprofileinfoapp_profile_site_app_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofileinfoapp",
            old_name="user",
            new_name="user_info",
        ),
    ]
